### ISSUE TITLE
Project name

### ISSUE THREAD

**Issue by rsaccon** [fxfactorial/ethereum-re#5]
Why is the project name (in `package.json` and `bsconfig.json`):
`@algebr/ethereum`
and not **ethereum-re** ?

**Comment by fxfactorial** [comment]
cause its good practice to namespace npm packages these days

**Comment by rsaccon** [comment]
ok, makes sense.

**Comment by fxfactorial** [comment]
@rsaccon I'm going to step back for a little bit while I'm learning a human language. As a general game plan, if you were interested, to basically copy paste the new functions in libNative.re code and put it in libJs.re and just using the examples as they are now.

**Comment by rsaccon** [comment]
Ok. Good luck with that. I will continue to explore this area, probably just implement what I need and keep posting here and provide PR. Right now my  local copy has some small changes, so I can keep my JS-first based toolchain: had to put in `bsconfig.json/entries` the `js` backend as first entry, so it gets picked up by bsb if I call it without `-backend` argument (what **parcel** and **vscode** in my toolchain do, vscode however could be easily reconfigured I think)
